import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntProvider } from "@/components/shared/AntProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Memory Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className}`}>
        <AntProvider>
          {children}
        </AntProvider>
      </body>
    </html>
  );
}
