import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntProvider } from "@/components/shared/AntProvider";
import { SocketProvider } from "@/context/socketContext";
import { ReduxProvider } from "@/context/reduxProvider";
import { Footer } from "antd/es/layout/layout";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Memory Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className}`}>
        <ReduxProvider>
          {/* <SocketProvider> */}
          <AntProvider>
            {children}
          </AntProvider>
          {/* </SocketProvider> */}
        </ReduxProvider>
      </body>
    </html>
  );
}
